# ===========================
# VET EXPERTS - USUARIOS MICROSERVICE
# ===========================
spring.application.name=vetexperts-usuarios-service
server.port=8081

# Perfil activo
spring.profiles.active=local

# ===========================
# JWT Configuration
# ===========================
jwt.secret=VetExpertsSecretKey2026MicroservicioUsuariosJWTTokenSeguro256bits!!
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer 

# ===========================
# SMTP (desarrollo)
# ===========================
mail.host=smtp.gmail.com
mail.port=587
mail.username=tu-correo@gmail.com
mail.password=tu-password-app
mail.sender=tu-correo@gmail.com
app.email.dev-mode=true
